name: Serverless CI/CD

on:
  push:
    branches: ['main']

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          echo "${{ secrets.MONGO_URL }}"
          echo "${{ secrets.AWS_SERVERLESS_ARN }}"

      # Setup nodejs 20.x
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install serverless framework
      - name: Install Serverless Framework
        run: npm install -g serverless

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::339712907640:role/Github-CICD-Dev-Role
          role-session-name: GitHubActions # Session name

      # Deploy serverless service
      - name: Deploy to AWS
        run: serverless deploy
